# Use hardened OpenJDK base image provided by Red Hat
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest

# Set default language to English
ENV LANGUAGE='en_US:en'

# Copy necessary libraries and artefacts into the image
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/
COPY --chown=185 target/quarkus-app/app-cds.jsa /deployments/quarkus/

# Advertise that the app is exposing port 8080
EXPOSE 8080

# Run the container as user 185
USER 185

# Set JAVA_OPTS
ENV JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:SharedArchiveFile=/deployments/app-cds.jsa "

# Tell startup script where to find the java archive to run
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar" 
