name: Build and test projects

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/**/*.yml'
      - '.gitignore'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/**/*.yml'
      - '.gitignore'

jobs:
  build-test-java17:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '17'
        project:
          - 'quarkus-aws-requeststreamhandler'
          - 'quarkus-azure-functions-http'
          - 'quarkus-funqy-azure'
    name: "build-test-${{ matrix.project }}-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Build
        working-directory: ${{ matrix.project }}
        run: ./mvnw -B clean verify -Dquarkus.http.test-port=8081 -Dmaven.compiler.release=${{ matrix.java }}

  build-test-java21:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
        project:
          - 'quarkus-rest-services'
          - 'quarkus-aws-lambda-http'
          - 'quarkus-google-cloud-functions-cloud-events'
          - 'quarkus-google-cloud-functions-http'
          - 'knative-quarkus-function-ce'
          - 'knative-quarkus-function-http'
          - 'quarkus-funqy-aws'
          - 'quarkus-funqy-gcp-cloud-events'
          - 'quarkus-funqy-gcp-http'
          - 'quarkus-funqy-standalone'
    name: "build-test-${{ matrix.project }}-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: Build
        working-directory: ${{ matrix.project }}
        run: ./mvnw -B clean verify -Dquarkus.http.test-port=8081 -Dmaven.compiler.release=${{ matrix.java }}