name: Simple app build and test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - 'showcase-templates.yaml'
      - 'scaffolder-templates/parasol-java-template/manifests/**'
      - 'scaffolder-templates/parasol-java-template/prompt-testing/**'
      - 'scaffolder-templates/parasol-java-template/docs/**'
      - 'scaffolder-templates/parasol-java-template/template.yaml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/dependabot-automerge.yml'
      - 'showcase-templates.yaml'
      - 'scaffolder-templates/parasol-java-template/manifests/**'
      - 'scaffolder-templates/parasol-java-template/prompt-testing/**'
      - 'scaffolder-templates/parasol-java-template/docs/**'
      - 'scaffolder-templates/parasol-java-template/template.yaml'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash
    working-directory: scaffolder-templates/parasol-java-template/skeleton

jobs:
  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '21'
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
    name: "jvm-build-test-${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven

      - name: "build-test-jvm-java${{ matrix.java }}"
        run: |
          ./mvnw -B clean verify \
            -Dquarkus.profile=ollama \
            -Dquarkus.test.profile=ollama,test \
            -Dquarkus.test.integration-test-profile=ollama,prod \
            -Dquarkus.http.host=0.0.0.0 \
            -Dquarkus.http.port=8080 \
            -Dmaven.compiler.release=${{ matrix.java }}